SPLIT_KEYBOARD = yes
MCU = atmega32u4
BOOTLOADER = caterina

# VIAL settings
VIA_ENABLE = yes
VIAL_ENABLE = yes
QMK_SETTINGS = no
VIAL_INSECURE = yes
LOCKING_SUPPORT = no

# Optimalization
LTO_ENABLE = yes

# Aditional functionality
NKRO_ENABLE = yes
TAP_DANCE_ENABLE = yes

CONSOLE_ENABLE = no
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = no
MAGIC_ENABLE = no
WPM_ENABLE = no
COMMAND_ENABLE = no
OLED_ENABLE = no
GRAVE_ESC_ENABLE = no
SPACE_CADET_ENABLE = no
STENO_ENABLE = no
API_SYSEX_ENABLE = no
AUDIO_ENABLE = no
BOOTMAGIC_ENABLE = no
